### ISSUE TITLE
help pls im newbee 

### ISSUE THREAD

**Issue by figurenok1** [waslost0/umbrella_parser#2]
pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by waslost0** [comment]
You need to change directory in cmd/powershell or open cmd/powershell from folder by pressing shift+right mouse button then  select  **Open command window here**

**Comment by figurenok1** [comment]
> You need to change directory in cmd/powershell or open cmd/powershell from folder by pressing shift+right mouse button then select **Open command window here**

хз почему но у меня просто открывается powershell и я не могу ничего туда написать(

**Comment by figurenok1** [comment]
> You need to change directory in cmd/powershell or open cmd/powershell from folder by pressing shift+right mouse button then select **Open command window here** тоже самое(

![image](https://user-images.githubusercontent.com/77461462/104712974-ee68fc00-572b-11eb-8eb6-fa9c3f27d629.png)

**Comment by waslost0** [comment]
Try  `pip install -r .\requirements.txt`

**Comment by figurenok1** [comment]
![image](https://user-images.githubusercontent.com/77461462/104720365-abac2180-5735-11eb-93f5-1fc42d9a9459.png)


> Try `pip install -r .\requirements.txt`

**Comment by waslost0** [comment]
Попробуй с cmd

**Comment by figurenok1** [comment]
> Попробуй с cmd

все та же фигня, друг( 
![image](https://user-images.githubusercontent.com/77461462/104733927-1c5c3980-5748-11eb-9cfb-8388f77dd810.png)

**Comment by waslost0** [comment]
Выведи список файлов `dir`
Напиши в [тг](https://t.me/waslost) если можешь
